package com.starlingapp.roundup.models.enums;

public enum TransactionSource {
    BRITISH_BUSINESS_BANK_FEES, CARD_FEE_CHARGE, CASH_DEPOSIT, CASH_DEPOSIT_CHARGE, CASH_WITHDRAWAL,
    CASH_WITHDRAWAL_CHARGE, CHAPS, CHEQUE, CICS_CHEQUE, CURRENCY_CLOUD, DIRECT_CREDIT, DIRECT_DEBIT,
    DIRECT_DEBIT_DISPUTE, INTERNAL_TRANSFER, MASTER_CARD, MASTERCARD_MONEYSEND, MASTERCARD_CHARGEBACK,
    MISSED_PAYMENT_FEE, FASTER_PAYMENTS_IN, FASTER_PAYMENTS_OUT, FASTER_PAYMENTS_REVERSAL,
    STRIPE_FUNDING, INTEREST_PAYMENT, NOSTRO_DEPOSIT, OVERDRAFT, OVERDRAFT_INTEREST_WAIVED,
    FASTER_PAYMENTS_REFUND, STARLING_PAY_STRIPE, ON_US_PAY_ME, LOAN_PRINCIPAL_PAYMENT, LOAN_REPAYMENT,
    LOAN_OVERPAYMENT, LOAN_LATE_PAYMENT, LOAN_FEE_PAYMENT, LOAN_INTEREST_CHARGE, SEPA_CREDIT_TRANSFER,
    SEPA_DIRECT_DEBIT, TARGET2_CUSTOMER_PAYMENT, FX_TRANSFER, ISS_PAYMENT, STARLING_PAYMENT,
    SUBSCRIPTION_CHARGE, OVERDRAFT_FEE, WITHHELD_TAX, ERRORS_AND_OMISSIONS, INTEREST_V2_PAYMENT
}
